CREATE TABLE comments (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  authorName TEXT NOT NULL,
  title TEXT,
  content TEXT NOT NULL,
  reviewed Boolean set False,
  date_created TIMESTAMP DEFAULT now() NOT NULL,
 articlesId INTEGER REFERENCES articles(id) ON DELETE CASCADE NOT NULL
);